theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true
baseURL = "https://pbs-mentoring-3era-edicion.github.io/mentoring-blog/"


[pagination]
pagerSize = 3

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]
