theme = "blowfish"
defaultContentLanguage = "en"

[languages]
[languages.en]
languageCode = "en-US"
languageName = "English"
weight = 1

[languages.es]
languageCode = "es-ES"
languageName = "Español"
weight = 2
enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true
baseURL = "https://pbs-mentoring-3era-edicion.github.io/mentoring-blog/"

[pagination]
pagerSize = 20

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]
