languageCode = "es"
languageName = "Spanish"
weight = 1
title = "Kathya Pérez - Portafolio"

[params]
displayName = "ES"
isoCode = "es"
rtl = false
description = "Portafolio de Kathya Pérez - Estudiante de Ingeniería en Desarrollo de Software apasionada por la programación back-end y la creación de soluciones tecnológicas innovadoras."
dateFormat = "2 January 2006"
logo = "img/kathya-logo.png"

  [params.author]
  name = "Kathya Pérez"
  image = "img/kperez_avatar.jpeg"
  headline = "Estudiante de Ingeniería en Desarrollo de Software | Desarrolladora Backend"
  bio = "Estudiante de Ingeniería en Desarrollo de Software apasionada por la programación y la creación de soluciones tecnológicas innovadoras. Capaz de manejar con facilidad HTML, PHP, CSS y C#, con experiencia en Visual Studio y Visual Studio Code para el desarrollo de aplicaciones, sitios y páginas web. Destaco por mi responsabilidad, liderazgo y capacidad para trabajar en equipo."

    [[params.author.links]]
    email = "kathyaperez117@gmail.com"

    [[params.author.links]]
    github = "https://github.com/kathyaperez"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/kathya-perez117"

    [[params.author.links]]
    phone = "7691-8430"
