languageCode = "en"
languageName = "English"
weight = 1
title = "Mentoring Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "This is the official journal of our mentoring journey: we document, step by step, both my mentee’s experience and my own, from the very first lessons to the challenges of production."
dateFormat = "2 January 2006"
logo = "img/hc_logo.png"

  [params.author]
  name = "Alejandro Solares"
  image = "img/19656917.png"
  headline = "Cloud Specialist | Azure | AWS | GCP"
  bio = "An enthusiast of researching new technologies that enhance my skills as a DevSecOps Engineer and empower the teams I work with to become industry game-changers, always committed to delivering critical solutions and innovative ideas in my projects, and continually striving to advance my knowledge and abilities in open-source solutions, hybrid cloud, cost optimization, bare-metal, and orchestration."

    [[params.author.links]]
    email = "josue.alejandro.solares@gmail.com"

    [[params.author.links]]
    github = "https://github.com/AlejandroSolares"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/josue-alejandro-solares-rodriguez/"

