languageCode = "en"
languageName = "English"
weight = 1
title = "Kathya Pérez - Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Portfolio of Kathya Pérez - Software Engineering Student passionate about back-end development and creating innovative technological solutions."
dateFormat = "2 January 2006"
logo = "img/kathya-logo.png"

  [params.author]
  name = "Kathya Pérez"
  image = "img/kperez_avatar.jpeg"
  headline = "Software Engineering Student | Backend Developer"
  bio = "Student of Software Engineering passionate about programming and creating innovative technological solutions. Proficient in HTML, PHP, CSS, and C#, with experience using Visual Studio and Visual Studio Code for developing applications, sites, and web pages. Known for responsibility, leadership, and teamwork capabilities."

    [[params.author.links]]
    email = "kathyaperez117@gmail.com"

    [[params.author.links]]
    github = "https://github.com/kathyaperez"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/kathya-perez117"

    [[params.author.links]]
    phone = "7691-8430"
