languageCode = "en"
languageName = "English"
weight = 1
title = "Mentoring Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "This is the official journal of our mentoring journey: we document, step by step, both my mentee’s experience and my own, from the very first lessons to the challenges of production."
dateFormat = "2 January 2006"
logo = "assets/img/hc_logo.png"

  [params.author]
  name = "Red Blowfish"
  image = "img/avatar.png"
  headline = "This is my website with my links"
  bio = "A little bit about you"

    [[params.author.links]]
    email = "josue.alejandro.solares@gmail.com"

    [[params.author.links]]
    github = "https://github.com/AlejandroSolares"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/josue-alejandro-solares-rodriguez/"

["params.author"]
name = "Alejandro Solares"
image = "assets/img/19656917.png"
headline = "Cloud Specialist | Azure | AWS | GCP"
