languageCode = "en"
languageName = "English"
weight = 1
title = "Kathya Pérez - Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Portfolio of Kathya Pérez - Software Engineering Student passionate about back-end development and creating innovative technological solutions."
dateFormat = "2 January 2006"
logo = "img/kathya-logo.png"

